FROM cuda-ros-base:foxy

# Install dependencies
RUN apt update && apt install -y \
    curl \
    git \
    build-essential \
    clang \
    && rm -rf /var/lib/apt/lists/*

# Install Rust and Cargo
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Clone and build zenoh-plugin-dds
RUN git clone https://github.com/eclipse-zenoh/zenoh-plugin-dds.git

RUN cd zenoh-plugin-dds && \
    cargo install --locked --path zenoh-bridge-dds